### ISSUE TITLE
cannot login into windows servers through rdpgw by windows remote desktop client

### ISSUE THREAD

**Issue by softputer** [bolkedebruin/rdpgw#105]
Hello,  i have deployed rdpgw to a linux server and it works well
i can run Microsoft Remote Desktop on mac to login into winodws servers through rdpgw successfully
but when i want to login into those windows server from windows remote desktop, it just failed with no infos

i wonder is it ok to login into windows server through rdpgw from windows remote desktop or am i doing something wrong?

**Comment by bolkedebruin** [comment]
Read the caveats for the windows client and make sure you applied all requirements. 

No info typically means invalid certificate or invalid login type. You are required to use openid or kerberos.
