### ISSUE TITLE
How to us it?Enable rdpgw locally

### ISSUE THREAD

**Issue by xiaonaiquan** [bolkedebruin/rdpgw#110]
![image](https://github.com/bolkedebruin/rdpgw/assets/16412671/1be41734-b63e-4742-9936-1e58cde941bf)

![image](https://github.com/bolkedebruin/rdpgw/assets/16412671/ff359a64-4361-4718-8d9e-53950a468653)

rdpgw.yml:
”
Server:
 Authentication:
  - local
 CertFile: /opt/rdpgw/fullchain.crt
 KeyFile: /opt/rdpgw/private.pem
 GatewayAddress: localhost:9443
 Port: 9443
 Hosts:
  - 192.168.61.129:3389
 RoundRobin: false
 SessionKey: thisisasessionkeyreplacethisjetz
 SessionEncryptionKey: thisisasessionkeyreplacethisnunu
AuthSocket: /tmp/rdpgw-auth.sock
OpenId:
 ProviderUrl: http://keycloak:8080/auth/realms/rdpgw
 ClientId: rdpgw
 ClientSecret: 01cd304c-6f43-4480-9479-618eb6fd578f
Client:
 UsernameTemplate: "{{ username }}"
Security:
  PAATokenSigningKey: prettypleasereplacemeinproductio
Caps:
 TokenAuth: false
“

This is my code to verify the pam program：
“
package main

import (
	"errors"
	"log"
	"os"

	"github.com/msteinert/pam"
)

func AuthPAM(username, password string) (bool, error) {
	handler := func(s pam.Style, msg string) (string, error) {
		switch s {
		case pam.PromptEchoOff:
			return password, nil
		case pam.PromptEchoOn, pam.ErrorMsg, pam.TextInfo:
			return "", nil
		}
		return "", errors.New("Unrecognized message style")
	}

	t, err := pam.StartFunc("rdpgw", username, handler)
	if err != nil {
		log.Println("init pam error: ", err)
		return false, err
	}

	err = t.Authenticate(0)
	if err != nil {
		log.Println("pam authenticate error: ", err)
		return false, err
	}
	return true, nil
}

func main() {
	if len(os.Args) != 3 {
		log.Println(os.Args[0], "username", "password")
		return
	}

	res, err := AuthPAM(os.Args[1], os.Args[2])
	if err != nil {
		log.Println("AuthPAM error: ", err)
		return
	}

	log.Println("Auth ", res)
}
”

How do I connect to the remote machine through it?like freerdp.
My rdpgw-auth program is working correctly. The pam program is also working correctly.

**Comment by bolkedebruin** [comment]
For PAM authentication there is a working docker-compose. Have a look at: https://github.com/bolkedebruin/rdpgw/blob/master/dev/docker/docker-compose-local.yml

**Comment by xiaonaiquan** [comment]
> For PAM authentication there is a working docker-compose. Have a look at: https://github.com/bolkedebruin/rdpgw/blob/master/dev/docker/docker-compose-local.yml

It's the same. No output.I don't know how to use freerdp to link. 
"wfreerdp.exe /gateway:g:192.168.61.131:9443,u:xxx,p:xxxx /v:192.168.61.129:3389 /log-level:TRACE > stdout.log"
It doesn't work

**Comment by xiaonaiquan** [comment]
@bolkedebruin Can you take a look?

**Comment by bolkedebruin** [comment]
@xiaonaiquan there is little to go on and the docker-compose works with the standard Mac client. Your issue seems to be client side which is out of scope of this project. 

So unless you provide elaborate logs that indicate an issue with rdpgw and you tried this with other clients than freerdp, I will need to close this issue unfortunately.

**Comment by xiaonaiquan** [comment]
> @xiaonaiquan there is little to go on ("it doesn't work", doesn't help anyone to find your issue) and the docker-compose works with the standard Mac client. Your issue seems to be client side which is out of scope of this project.
> 
> So unless you provide elaborate logs that indicate an issue with rdpgw and you tried this with other clients than freerdp, I will need to close this issue unfortunately.

first , "docker-ubuntu-xrdp-mate-rdpgw" ，It doesn't work
https://private-user-images.githubusercontent.com/16412671/322243374-e10e15f7-bf61-44d3-aac8-d6c3320ce619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzE2NjgsIm5iZiI6MTcxMzI3MTM2OCwicGF0aCI6Ii8xNjQxMjY3MS8zMjIyNDMzNzQtZTEwZTE1ZjctYmY2MS00NGQzLWFhYzgtZDZjMzMyMGNlNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEyNDI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMmZmMGRiMTVmNWY2NDhhNzkyMWM5NDg5ZGEyNjA2ZjQyYTU5YTUzOTlkYmQyMGE0YmMxMDYyNmFiZmNkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVVH_CxN8b3B-eeSlMYsxPLYYdHcunDI06r3uXUvz-o

**Comment by bolkedebruin** [comment]
What is 

"docker-ubuntu-xrdp-mate-rdpgw" 

? An image? Where did you get this from?

**Comment by xiaonaiquan** [comment]
> What is
> 
> "docker-ubuntu-xrdp-mate-rdpgw"
> 
> ? An image? Where did you get this from?

<img width="613" alt="image" src="https://github.com/bolkedebruin/rdpgw/assets/16412671/b89b7135-46b1-48df-952e-605a851fc619">

**Comment by bolkedebruin** [comment]
You are using the openid version of the docker compose. 

Use https://github.com/bolkedebruin/rdpgw/blob/master/dev/docker/docker-compose-local.yml

**Comment by xiaonaiquan** [comment]
> You are using the openid version of the docker compose.
> 
> Use https://github.com/bolkedebruin/rdpgw/blob/master/dev/docker/docker-compose-local.yml

I'm just telling you what it is, I'm sure it's using local. Can you try and see if this image works properly?

**Comment by bolkedebruin** [comment]
![Screenshot 2024-04-16 at 17 03 24](https://github.com/bolkedebruin/rdpgw/assets/4282712/dfe32a92-c13b-426c-b67b-b713a6e016a4)

It works.
