### ISSUE TITLE
when i was build

### ISSUE THREAD

**Issue by zhaomangang** [bolkedebruin/rdpgw#12]
this is error:
go: github.com/coreos/go-oidc/v3@v3.0.0-alpha.1: Get "https://goproxy.cn/github.com/coreos/go-oidc/v3/@v/v3.0.0-alpha.1.mod": dial tcp: lookup goproxy.cn on 223.5.5.5:53: read udp 10.0.8.156:33324->223.5.5.5:53: i/o timeout

is it because my device not connect to intrernet?
If that's the case,pelease tell me how build when i was offline. thinks!

**Comment by bolkedebruin** [comment]
This is beyond the scope of the project. Maybe this will help: https://www.reddit.com/r/golang/comments/jquf12/go_offline_development_best_practicestips/
