### ISSUE TITLE
make tls optional

### ISSUE THREAD

**Issue by mrfreezer** [bolkedebruin/rdpgw#21]
since we are using ssl/tls-offload via firewall it would be a nice to be able to turn off the tls encryption.

and as a bonus evaluating something like the x-proto and the x-forwarded-for headers and logging / displaying them would be a pretty large plus :)

ingo

**Comment by bolkedebruin** [comment]
If you create a patch for these (separate), I’ll add it. Configuration item can be “DisableTLSForOffloading”. It should be “false” by default.

**Comment by bolkedebruin** [comment]
What would you evaluate for on X-Proto/Forwarder-for?
