### ISSUE TITLE
go: error loading module requirements

### ISSUE THREAD

**Issue by uana777** [bolkedebruin/rdpgw#22]
make
go mod tidy
go: finding github.com/spf13/cobra v1.1.3
go: finding github.com/spf13/viper v1.7.1
go: finding github.com/patrickmn/go-cache v2.1.0+incompatible
go: finding github.com/gorilla/websocket v1.4.2
go: finding github.com/coreos/go-oidc/v3 v3.0.0
go: finding github.com/gorilla/sessions v1.2.1
go: finding github.com/square/go-jose/v3 v3.0.0-20200630053402-0a67ce9b0693
go: finding github.com/prometheus/client_golang v1.10.0
go: golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: github.com/coreos/go-oidc/v3@v3.0.0: unknown revision v3.0.0
go: github.com/spf13/viper@v1.7.1: unknown revision v1.7.1
go: github.com/spf13/cobra@v1.1.3: unknown revision v1.1.3
go: github.com/gorilla/websocket@v1.4.2: unknown revision v1.4.2
go: github.com/prometheus/client_golang@v1.10.0: unknown revision v1.10.0
go: github.com/patrickmn/go-cache@v2.1.0+incompatible: unknown revision v2.1.0
go: github.com/gorilla/sessions@v1.2.1: unknown revision v1.2.1
go: error loading module requirements
Makefile:51: recipe for target 'mod' failed
make: *** [mod] Error 1

**Comment by uana777** [comment]
That my go version is :
go version go1.12.5 linux/amd64

**Comment by bolkedebruin** [comment]
Your go version is too old. You will need at least 1.16.
