### ISSUE TITLE
docker-compose is using old keycloak-version

### ISSUE THREAD

**Issue by Azathoth88** [bolkedebruin/rdpgw#28]
A deprecated keycloak image is used in the docker compose. For security reasons, this should be updated. See also: https://quay.io/repository/keycloak/keycloak?tag=latest&tab=tags

**Comment by bolkedebruin** [comment]
Can you provider a PR of course ;-)

**Comment by Azathoth88** [comment]
Sorry, I'm product owner and not a developer. I'm very familiar with jira and confluence. I only use Github to report bugs or feature requests. 
When I get the chance, I'll take a look at creating PR or have our developers show me how to do it.

**Comment by bolkedebruin** [comment]
Well it might be time topick up some skills then... in the mean time I have fixed this.
