### ISSUE TITLE
Starting problem

### ISSUE THREAD

**Issue by Uzzi** [bolkedebruin/rdpgw#29]
Hi, I've this error after docker-compose up from /opt/rdpgw/dev/docker:
`Cannot get oidc provider: Get "http://localhost:8080/auth/realms/rdpgw/.well-known/openid-configuration": dial tcp 127.0.0.1:8080: connect: connection refused`

How can I fix it?
Thank you

**Comment by bolkedebruin** [comment]
You will need to wait until keycloak comes up.

**Comment by Uzzi** [comment]
`docker-keycloak-1  | 14:05:49,360 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
docker-rdpgw-1     | 2021/12/28 14:06:06 Cannot get oidc provider: Get "http://localhost:8080/auth/realms/rdpgw/.well-known/openid-configuration": dial tcp 127.0.0.1:8080: connect: connection refused
`

**Comment by bolkedebruin** [comment]
You do not seem to be runnibg my docker config. The providerUrl https://github.com/bolkedebruin/rdpgw/blob/master/dev/docker/rdpgw.yaml#L12 and yours is not equal to that. It should connect to `http://keycloak/xxx` not to `localhost`

**Comment by Uzzi** [comment]
I've changed to http://keycloak/xxx but server keycloak not found.
