### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by chengjixin** [bolkedebruin/rdpgw#37]
when Setup 5/13,Timeout exception found，The specific information is: fatal：go: github.com/coreos/go-oidc/v3@3.0.0：Get "https:proxy.golang.org/github.com/coreos/go-oidc/v3/@v/v3.0.0.mod": dial tcp 142.251.42.241:44 : i/o timeout

**Comment by bolkedebruin** [comment]
Please check again if this issue persists.
