### ISSUE TITLE
Not working with remmina with rdp Gateway 

### ISSUE THREAD

**Issue by dsrinibanyan** [bolkedebruin/rdpgw#41]
Hi there,

Very useful project. I appreciate the effort her.
I was trying to use this implementation on linux and tried rdp with remmina. But it seems to fail due to NTLM negotiation failures. I see people getting it to work, not sure what am I missing.  Plz help.

21:26:54:263] [51107:52041] [DEBUG][com.winpr.sspi] - InitSecurityInterfaceExA
[21:26:54:263] [51107:52041] [DEBUG][com.winpr.sspi.NTLM] - change
state from NTLM_STATE_INITIAL to NTLM_STATE_INITIAL
[21:26:54:263] [51107:52041] [DEBUG][com.winpr.sspi.NTLM] - change
state from NTLM_STATE_INITIAL to NTLM_STATE_NEGOTIATE
[21:26:54:263] [51107:52041] [DEBUG][com.winpr.sspi.NTLM] - Write
flags [0xe20882b7]
NTLMSSP_NEGOTIATE_UNICODE|NTLMSSP_NEGOTIATE_OEM|NTLMSSP_REQUEST_TARGET|NTLMSSP_NEGOTIATE_SIGN|NTLMSSP_NEGOTIATE_SEAL|NTLMSSP_NEGOTIATE_LM_KEY|NTLMSSP_NEGOTIATE_NTLM|NTLMSSP_NEGOTIATE_ALWAYS_SIGN|NTLMSSP_NEGOTIATE_EXTENDED_SESSION_SECURITY|NTLMSSP_NEGOTIATE_VERSION|NTLMSSP_NEGOTIATE_128|NTLMSSP_NEGOTIATE_KEY_EXCH
[21:26:54:263] [51107:52041] [DEBUG][com.winpr.sspi.NTLM] - change
state from NTLM_STATE_NEGOTIATE to NTLM_STATE_CHALLENGE
[21:26:54:263] [51107:52041] [DEBUG][com.freerdp.core.gateway.rdg] -
Unexpected NTLM challenge HTTP status: 101
[21:26:54:264] [51107:52041] [ERROR][com.freerdp.core.nego] - Protocol
Security Negotiation Failure
[21:26:54:264] [51107:52041] [ERROR][com.freerdp.core] -
rdp_client_connect:freerdp_set_last_error_ex
ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[21:26:54:264] [51107:52041] [ERROR][com.freerdp.core.connection] -
Error: protocol security negotiation or connection failure
** (org.remmina.Remmina:51107): DEBUG: 21:26:54.417: [postcommand] (null)
** (org.remmina.Remmina:51107): DEBUG: 21:26:54.417: [postcommand] updated to:

**Comment by gemone** [comment]
Try [`FreeRDP`](https://github.com/FreeRDP/FreeRDP).

If you can connect, it may be the problem of `remmina` itself. The problem recurs when connecting to Windows10.

**Comment by dsrinibanyan** [comment]
I fixed the issue. That's because freerdp expects NTLM exchanges. But the same is not required on windows or mac.
