### ISSUE TITLE
How to disable Open-ID

### ISSUE THREAD

**Issue by MaFreiberger** [bolkedebruin/rdpgw#43]
Hello,

i want to use RDPGW as RDP-Gateway for a office. I have created a AlmaLinux-VM and compiled it. When starting the binary, it throws a error

[myuser@RDPGWVM bin]$ ./rdpgw
2022/07/07 18:51:03 Cannot get oidc provider: Get "/.well-known/openid-configuration": unsupported protocol scheme ""

because i don't want to use openid, i would like to disable that whole functionality. How to do that?

By the way, the project, at least the config-file needs more documentation.

Thank you

**Comment by bolkedebruin** [comment]
You cannot disable OpenID currently, If you would like to authenticate against AD/LDAP (the typical use case for this) you can setup Keycloak to do federation. See Plain user/pwd isn't as simple as it sounds. If you would like to authenticate against AD/LDAP you can setup Keycloak to do federation for AD/LDAP, see for example: https://dmc.datical.com/administer/configure-keycloak-ldap.htm

**Comment by MaFreiberger** [comment]
First, thanks a lot for developing this project, i#m waiting since 10 years that someone is doing it. MS-RDP-GW is a tool that really needs a FOSS alternative. How many small companies end up buying a expensive MS-Server just to get their infrastructure available. AD and RDP ARE really useful and easy to use, also in a mixed or FOSS only environment. AD-implementations are available since more then 10years, but the RDP-GW was missing.


About usage of Keycloak. I thought that you had a way of doing that. And that it ends up with a bunch of tools glued together. The problem that is now happening is when Admins like me, collide with developers like you and we did not understand each other. Which happens often in such cases.
To minimise those effects and speed up the usage, pls. don't underestimate good documentation. Admins are no coder and coder seldom are admins, so the view on a project is different.
From the beginning it should be clear what is needed to deploy that project and how to come to working solution. A manual from start to end of a typical deployment in a MS-domaine would be a good first step.
If i have the time and manage to get it working, i could give you my docu/ticket about the deployment as a template for a documentation.

Again, thanks a lot.

**Comment by gemone** [comment]
@MaFreiberger Hi, I have made an internal modified version, which only needs to modify the method of `PAAToken` generation and verification.

This function is easy to implement, but it seems to be inconsistent with the direction of this project.

**Comment by bolkedebruin** [comment]
rdpgw can now verify users against PAM if you configure 'local' Authentication and run `rdpgw-auth` which is included now.

**Comment by bigbenz8** [comment]
> rdpgw can now verify users against PAM if you configure 'local' Authentication and run `rdpgw-auth` which is included now.

I still don't know how to use it, can I write a brief usage document? thanks .
