### ISSUE TITLE
Disable domain certificate verification ? 

### ISSUE THREAD

**Issue by maestro1315** [bolkedebruin/rdpgw#45]
The website/domain cert is managed at the load balancer level. There is no control over that and the certificate can't be shared. I'm unable to provide a valid certificate in the rdpgw.yaml file. Is there any way around that ?

**Comment by bolkedebruin** [comment]
This is now part of master. You can disable TLS by setting "disableTLS: true". See the example template for details. Please test if this works as I have not been able to test it.

**Comment by maestro1315** [comment]
> This is now part of master. You can disable TLS by setting "disableTLS: true". See the example template for details. Please test if this works as I have not been able to test it.

I did some quick testing and it doesn't appear to work. It's still attempting to serve up the certificate from the rdpgw.

**Comment by bolkedebruin** [comment]
Please confirm this with the version from master or docker latest, I've double checked and it works on my side.

**Comment by bolkedebruin** [comment]
And it now needs to be DisableTLS note the the capital D.
