### ISSUE TITLE
Failed to start wtihout tls

### ISSUE THREAD

**Issue by zznty** [bolkedebruin/rdpgw#49]
```
2022/09/01 16:12:31 Cookies are used as session storage
2022/09/01 16:12:31 Starting remote desktop gateway server
2022/09/01 16:12:31 TLS disabled - rdp gw connections require tls, make sure to have a terminator
2022/09/01 16:12:31 ListenAndServe: open : no such file or directory
```

getting this while trying to start docker container
happens only when tls is disabled (im using traefik as tls terminating proxy)

**Comment by zznty** [comment]
actually just had to turn on https for this service
but issue with disabled tls still persists

**Comment by bolkedebruin** [comment]
I'll have a look. Did you test with latest master?

**Comment by zznty** [comment]
> Did you test with latest master?

yes, seems to be working with `http.ListenAndServe` but not with server instance

**Comment by bolkedebruin** [comment]
Fixed in master
