### ISSUE TITLE
Enable logs to stdout/stderr

### ISSUE THREAD

**Issue by thea1exei** [bolkedebruin/rdpgw#51]
Greetings.
Can you tell me how to enable logs in rdpgw.
Built and raised from the wizard in the docker, trying to check authentication connection via keycloak, but it gives a security error. Maybe the logs will tell me more details.

Thanks.
![image](https://user-images.githubusercontent.com/11307378/188453416-3b8252a2-39b8-4d4c-a77d-618679aea854.png)

update:
I set up this connection, client -> https:443(public cert domain.com) -> reverse proxy -> https:9443 -> rdpgw -> .
rdpgw -> keycloak in docker http://keycloak:8080/realms/test
rdpgw -> rds server :3389 + internal cert (domain.local)

**Comment by bolkedebruin** [comment]
logs are by default enabled and log to stderr/stdout. 

If you are using mstsc on a recent windows installation it is required that you trust the certificate issued by the gateway and the rds server, otherwise the client won't connect.

**Comment by thea1exei** [comment]
Thank you.
It was my mistake, on the reverse proxy proxying was configured through http stream, and should be through tcp
The error occurred when the reverse proxy was nginx, I configured haproxy in tcp mode and the connection went through.
