### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by B-Eddine** [bolkedebruin/rdpgw#52]
Hello,
i try to install rdpgw in ubuntu server and it fails.
here's the issue
thanks by advance

#make
go mod tidy -compat=1.19
flag provided but not defined: -compat
usage: go mod tidy [-v]
Run 'go help mod tidy' for details.
make: *** [Makefile:53: mod] Error 2

**Comment by bolkedebruin** [comment]
make sure to run a recent "go" version. You might need to install a new one depending the version you have in your server.

```
% go mod tidy --help
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
```
