### ISSUE TITLE
keycloak:8080 failing

### ISSUE THREAD

**Issue by fruizhms** [bolkedebruin/rdpgw#61]
Am i supposed to create a host entry on the host file for keycloak -> 127.0.0.1 ?

For some reason keycloak:8080/auth doesn't work hence localhost:9443/connect fails because it redirects me to keycloak:8080 for authentication. 

If i enter localhost:8080/auth. that works fine without issues.
If i enter keycloak:8080/auth, i get page not found error.

**Comment by fruizhms** [comment]
as a workaround for now, i added 127.0.0.1 keycloak to host file. I can authenticate and download the rdp file now.

however when i attempt to open the rdp file i get

![image](https://user-images.githubusercontent.com/118473207/202523290-212ae76d-3329-49ae-8d72-e7f68e878481.png)

**Comment by bolkedebruin** [comment]
The Windows MS require a valid DNS entry and a certificate with a CN equalling the DNS name for gateway connections. I have no way to predict if your DNS is going to point to the right server unfortunately.
