### ISSUE TITLE
can i get help?

### ISSUE THREAD

**Issue by jumpwubo** [bolkedebruin/rdpgw#7]
hello, i use windows mstsc  client to connect to this rdpgw by  gateway method,  i want to get  some  gw account info from rdpgw, not rdp server account, but i have't analyse it. can give me some ideas?

**Comment by bolkedebruin** [comment]
Im not sure what you want to accomplish. The rdpgw supports checking authentication against an OpenID Connect provider (Keycloak, Google, Azure etc). Getting “info” is not a functionalty of the gateway, but I am unsure here what you mean by that. What kind of info do you look for?
