### ISSUE TITLE
Kerberos auth

### ISSUE THREAD

**Issue by veniamin-r** [bolkedebruin/rdpgw#73]
Hello!

I installed kerberos, added a principal (user) for rdpgw and made its keytab using ktutil (I tried 'kadmin(.local): ktadd' too, also tried to set read rights for group and user)...
I set kerberos as authentication method in yaml, but rdpgw always returns an error: "kerberos is configured but no keytab was specified".
Why can it be?

Thanks.

**Comment by bolkedebruin** [comment]
make sure to specify a `keytab` entry that points to your keytab file in the `kerberos` section of the yaml file.
