### ISSUE TITLE
Compile (make) errors

### ISSUE THREAD

**Issue by hyiin** [bolkedebruin/rdpgw#74]
I am using an Ubuntu server version 22.0 and am getting the following error when I tried to "make":

root@hv-rdpgw:/var/pkg/RDPGW/rdpgw-master# make
go mod tidy -compat=1.20
go build  -trimpath -tags '' -ldflags '' -o '/var/pkg/RDPGW/rdpgw-master/bin'/rdpgw ./cmd/rdpgw
go build  -trimpath -tags '' -ldflags '' -o '/var/pkg/RDPGW/rdpgw-master/bin'/rdpgw-auth ./cmd/auth
# github.com/bolkedebruin/rdpgw/cmd/auth
cmd/auth/auth.go:37:16: undefined: pam.StartFunc
cmd/auth/auth.go:37:70: undefined: pam.Style
cmd/auth/auth.go:39:12: undefined: pam.PromptEchoOff
cmd/auth/auth.go:41:12: undefined: pam.PromptEchoOn
cmd/auth/auth.go:41:30: undefined: pam.ErrorMsg
cmd/auth/auth.go:41:44: undefined: pam.TextInfo
make: *** [Makefile:39: /var/pkg/RDPGW/rdpgw-master/bin/rdpgw] Error 1

I found a similar posting in StackOverflow but with not detailed fix. Can someone help?

**Comment by archef2000** [comment]
you are missing `apt-get install -y libpam-dev`

**Comment by hyiin** [comment]
@archef2000 Thanks for replying. I did have the libpam0g-dev (v1.4.0) installed. To be certain I removed and re-installed the package, but I still got the  same error message.

**Comment by archef2000** [comment]
Maybe upgrade make, build-essentials, etc ?

**Comment by bolkedebruin** [comment]
Typically the includes are then at the wrong location.
