### ISSUE TITLE
Question: NPM settings for rdpgw after authentication i get nginx 503 errror

### ISSUE THREAD

**Issue by pbvdven** [bolkedebruin/rdpgw#76]
im trying to setup rdpgw with authentik openid behind Nginx Proxy Manager but after successful authentication it wont download the rdp but i get a nginx 503 error.

Log rdpgw keeps saying Identity SessionId: 47e2557d-0c8b-4f04-87fc-499dd00ecdd3, UserName: : Authenticated: false

Do i need some extra configuration in NPM i tried some different things but i cant get it working some help would be appreciated.`

i tried adding this what someone mentioned but no luck.
proxy_set_header Upgrade "websocket";
proxy_set_header Connection "Upgrade";

**Comment by bolkedebruin** [comment]
I haven't tried setting things up behind nginx (we used haproxy on kubernetes). Note that you need to enforce http1/1 (http2 isnt supported by the protocol) and that the method (GET/POST etc) by the client is non standard. Your proxy needs to be able to handle this.

**Comment by pbvdven** [comment]
Thanks for answering im going to try to set it to http1 default is http2 hoping thats the issue.

**Comment by bauspanderu** [comment]
I'm currently facing the same issue. My NPM Log says:
```
2026/02/18 21:51:03 [error] 2994#2994: *669431 upstream sent too big header while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: rdpgw.XXX.XXX, request: "GET /callback?code=9c3c4131e0844f97b6212b4756522934&state=db04dd86bb3a6eee16f9a0b4c8dc3a02 HTTP/1.1", upstream: "http://172.20.0.13:443/callback?code=9c3c4131e0844f97b6212b4756522934&state=db04dd86bb3a6eee16f9a0b4c8dc3a02", host: "rdpgw.XXX.XXX"
```

I fixed it by adding this to "Advanced" in the Proxy Host:
```
proxy_busy_buffers_size   512k;
proxy_buffers   4 512k;
proxy_buffer_size   256k;
```
