### ISSUE TITLE
Question: How can I use this realization of RDG without token auth?

### ISSUE THREAD

**Issue by endofreal** [bolkedebruin/rdpgw#8]
Hi!

I just need to connect to xrdp desktop stored in kubernetes cluster without expose any container port.

I would like to use this as classic remote desktop gateway with password authentication to store .rdp files non changed on users PC. Is it possible?

**Comment by MaFreiberger** [comment]
Same for me. Just plain user/pwd authentication via ActiveDirectory/LDAP.

**Comment by bolkedebruin** [comment]
Plain user/pwd isn't as simple as it sounds. If you would like to authenticate against AD/LDAP you can setup Keycloak to do federation for AD/LDAP, https://dmc.datical.com/administer/configure-keycloak-ldap.htm . It allows RDPGW not to deal with passwords and remain secure.

**Comment by bolkedebruin** [comment]
User passwd authentication is now possible against PAM (which supports ldap, ad etc)
