### ISSUE TITLE
Working docker-compose?

### ISSUE THREAD

**Issue by vampywiz17** [bolkedebruin/rdpgw#96]
Somebody able to share a working docker-compose (that use docker hub image, not localy builded) with volumes, port mapping, etc...

I try to figure out, how to set it with portainer stack, but no success....

**Comment by TEDSv** [comment]
https://github.com/archef2000/rdpgw

**Comment by vampywiz17** [comment]
@TEDSv 

Thanks, but it is a bit out of date not?

**Comment by bolkedebruin** [comment]
Docker compose files have been updated. Please read the instructions on how to use it.
